FIX: appEvents.off error when destroying controller:topic (#50)
Fixes an error when the willDestroy function of the
topic controller is called, where we weren't using the
correct appEvent.off parameters:

> Error: Assertion Failed: You must pass at least an object, event name, and method or target and method/method name to removeListener
> at assert (http://localhost:7357/assets/vendor.js:47587:15)
> at removeListener (http://localhost:7357/assets/vendor.js:23681:184)
> at Class.off (http://localhost:7357/assets/vendor.js:38627:33)
> at Class.willDestroy (http://localhost:7357/assets/plugins/discourse-shared-edits.js:258:24)
> at Class.superWrapper [as willDestroy] (http://localhost:7357/assets/vendor.js:41971:22)